### ISSUE TITLE
Auto-compile messages cannot reliably be suppressed

### ISSUE THREAD

**Issue by sfkleach** [cky/guile#3]
The difficulty in suppressing 'user-friendly' warnings even when using Guile non-interactively has been noted previously. As I am using Guile in a pipeline, where it processes stdin to stdout, it is critical that these messages can be cleanly suppressed, while other significant errors can be logged.

An option --no-warn-auto-compile (default in batch mode) would be appropriate to disable these messages that have real purpose.

(Since this is a blocker for my work, I would be happy to work on it.)

**Comment by cky** [comment]
Hi Stephen,

This repo is an unofficial mirror of the [official project](https://savannah.gnu.org/projects/guile/); GNU projects are discouraged from using GitHub, and no Guile maintainers check out this mirror. All discussions and patches should go to the [guile-devel](https://lists.gnu.org/mailman/listinfo/guile-devel) mailing list.

In particular, the issue you refer to may have been addressed in [this thread](https://lists.gnu.org/archive/html/guile-devel/2016-07/msg00034.html). I don't believe it's been merged in yet, but it's a good starting point for you to jump into the conversation and/or contribute further changes.

Hope this helps!

**Comment by sfkleach** [comment]
Nice reply - thanks!

**Comment by cky** [comment]
Cool, glad to be of help. :-)
